name: Tests
on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master

concurrency:
  group: ci-tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
      - name: Code fetch
        uses: actions/checkout@v4
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Run tests
        env:
          RAILS_ENV: test
          ADMIN_USERNAME: ADMIN
          ADMIN_PASSWORD: PASSWORD
          AWS_ACCESS_KEY_ID: STUB
          AWS_SECRET_ACCESS_KEY: STUB
          REDIS_URL: redis://localhost:6379/1
        run: bundle exec rspec ./spec
